### PR TITLE
FIX: TripSegment translatation props

### LINKED ISSUE #879: <TripSegment> to accept React.Node in props
We use `nitro`'s `Translate` and custom`DateTime` components and would like to use them as values in `TripSegment`.
## Expected Behavior
`departureTime`, `arrivalTime` and `duration` props should allow values of `React.Node` type 
## Current Behavior
only `string` type is supported

## Possible Solution
fix similar to https://github.com/kiwicom/orbit-components/pull/444

### PR DESCRIPTION
**Pull request by mainframev**
Closes #879 
<br/><br/><br/><url>LiveURL: https://orbit-components-mainframe-tripsegment.surge.sh</url>

### CODE REVIEW

File: src/TripSegment/index.js.flow [hunk 1]
```diff
@@ -18,11 +18,11 @@ export type Props = {|
   ...Globals,
   +children: React$Node,
   +carrier: Carrier,
-  +departure: string,
-  +departureTime: string,
-  +arrival: string,
-  +arrivalTime: string,
-  +duration: string | number,
+  +departure: React.Node,
```
Comment (wEprous) [inline src/TripSegment/index.js.flow]: I think that using `Translate` type should be enough. See `common.js.flow`.

File: src/TripSegment/README.md [hunk 2]
```diff
@@ -25,14 +25,14 @@ After adding import into your project you can use it simply like:
...
+| **arrival**       | `Translation`           |         | The arrival city name and short code.                                                                                                                                                 |
+| **arrivalTime**   | `Translation`           |         | The arrival time.                                                                                                                                                                     |
+| **carrier**       | `Carrier`               |         | It's used to render proper icon in the Milestone, by Carrier type. [`See Carrier type`](https://github.com/kiwicom/orbit-components/tree/master/src/CarrierLogo#user-content-carrier) |
+| **children**      | `Translation`           |         | The content of the component.                                                                                                                                                         |
```
Comment (wEprous) [inline src/TripSegment/README.md]: Revert plz 🙏 children is still node

Comment (mainframev) [reply src/TripSegment/README.md]: it's still node, just mistake by copy-paste in documentation.
