### PR TITLE
FIX: Modal scroll and height

### LINKED ISSUE #361: <Modal /> always 100% screen height
<Modal /> has always 100% screen height

## Expected Behavior
<Modal /> should stretch according to its content

## Current Behavior
It has always `height: calc( 100% - 32px - 0px );`

screen shot 2018-09-19 at 09 33 13

### LINKED ISSUE #364: <ModalHeader /> has 100% height of screen
## Expected Behavior
ModalHeader should stretch according to its content

## Current Behavior
It pushes Modal content down to non visible area

screen shot 2018-09-19 at 09 58 25

### PR DESCRIPTION
**Pull request by wEprous**
Closes #364 
Close #361

### CODE REVIEW

File: src/Modal/index.js [hunk 1]
```diff
@@ -168,6 +166,7 @@ const ModalWrapperContent = styled.div`
     position: relative;
     border-radius: ${({ theme }) => theme.orbit.borderRadiusNormal};
     padding-bottom: 0;
+    height: auto;
```
Comment (tomashapl) [inline src/Modal/index.js]: please remove
