### PR TITLE
DEV: Refactor Modal subcomponents to React hooks

### LINKED ISSUE #1344: Attempts to access this ref will fail. Did you mean to use React.forwardRef, Check the render method of `ModalFooter`
I am seeing this error message a lot in the console log.

It happens for usage like

```
 <ModalFooter flex={['0 0 auto', '1 1 100%']}>
        ...
 </ModalFooter>
``` 

removing flex, will remove the error message.

### PR DESCRIPTION
**Pull request by vepor**
Closes #1344 
<br/><br/><br/><url>LiveURL: https://orbit-components-dev-refactor-modal-component-hooks.surge.sh</url>

### CODE REVIEW

**Comment by tbergq** [comment]
Any chance of having this merged soon? 👼

**Comment by vepor** [comment]
@tbergq will be merged & released today 🙂

File: src/Modal/ModalFooter/index.js [hunk 1]
```diff
@@ -60,72 +63,55 @@ StyledModalFooter.defaultProps = {
...
+  therefore, it's bypassed via declaring it in on this component
+ */
+const WrappedChildren = ({ children, flex = "0 1 auto" }) => {
+  if (!Array.isArray(children)) return children;
+  return React.Children.map(children, (child, key) => {
+    if (child) {
+      return (
+        <StyledChild flex={getChildFlex(flex, key)}>
+          {React.cloneElement(child, {
+            ref: child.red
```
Comment (filipdanisko) [inline src/Modal/ModalFooter/index.js]: Typo here?
